name: flutter_tree_demo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.3
  flutterflow_tree_view:
    path: ..
  text_search: 1.0.1

flutter:
  uses-material-design: true
