name: flutterflow_tree_view
version: 2.1.0
description: A widget that visualizes a tree structure.
repository: https://github.com/FlutterFlow/flutter_searchable_treeview
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
